# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ub/Desktop/QT_SDR/build

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ub/Desktop/QT_SDR

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ub/Desktop/QT_SDR/CMakeFiles /home/ub/Desktop/QT_SDR/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ub/Desktop/QT_SDR/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named qt

# Build rule for target.
qt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qt
.PHONY : qt

# fast build rule for target.
qt/fast:
	$(MAKE) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/build
.PHONY : qt/fast

#=============================================================================
# Target rules for targets named qt_autogen

# Build rule for target.
qt_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qt_autogen
.PHONY : qt_autogen

# fast build rule for target.
qt_autogen/fast:
	$(MAKE) -f CMakeFiles/qt_autogen.dir/build.make CMakeFiles/qt_autogen.dir/build
.PHONY : qt_autogen/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o

.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i

.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s

.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

qt_autogen/mocs_compilation.o: qt_autogen/mocs_compilation.cpp.o

.PHONY : qt_autogen/mocs_compilation.o

# target to build an object file
qt_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/qt_autogen/mocs_compilation.cpp.o
.PHONY : qt_autogen/mocs_compilation.cpp.o

qt_autogen/mocs_compilation.i: qt_autogen/mocs_compilation.cpp.i

.PHONY : qt_autogen/mocs_compilation.i

# target to preprocess a source file
qt_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/qt_autogen/mocs_compilation.cpp.i
.PHONY : qt_autogen/mocs_compilation.cpp.i

qt_autogen/mocs_compilation.s: qt_autogen/mocs_compilation.cpp.s

.PHONY : qt_autogen/mocs_compilation.s

# target to generate assembly for a file
qt_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/qt_autogen/mocs_compilation.cpp.s
.PHONY : qt_autogen/mocs_compilation.cpp.s

sdr.o: sdr.cpp.o

.PHONY : sdr.o

# target to build an object file
sdr.cpp.o:
	$(MAKE) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/sdr.cpp.o
.PHONY : sdr.cpp.o

sdr.i: sdr.cpp.i

.PHONY : sdr.i

# target to preprocess a source file
sdr.cpp.i:
	$(MAKE) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/sdr.cpp.i
.PHONY : sdr.cpp.i

sdr.s: sdr.cpp.s

.PHONY : sdr.s

# target to generate assembly for a file
sdr.cpp.s:
	$(MAKE) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/sdr.cpp.s
.PHONY : sdr.cpp.s

sdrworker.o: sdrworker.cpp.o

.PHONY : sdrworker.o

# target to build an object file
sdrworker.cpp.o:
	$(MAKE) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/sdrworker.cpp.o
.PHONY : sdrworker.cpp.o

sdrworker.i: sdrworker.cpp.i

.PHONY : sdrworker.i

# target to preprocess a source file
sdrworker.cpp.i:
	$(MAKE) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/sdrworker.cpp.i
.PHONY : sdrworker.cpp.i

sdrworker.s: sdrworker.cpp.s

.PHONY : sdrworker.s

# target to generate assembly for a file
sdrworker.cpp.s:
	$(MAKE) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/sdrworker.cpp.s
.PHONY : sdrworker.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... qt"
	@echo "... qt_autogen"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... qt_autogen/mocs_compilation.o"
	@echo "... qt_autogen/mocs_compilation.i"
	@echo "... qt_autogen/mocs_compilation.s"
	@echo "... sdr.o"
	@echo "... sdr.i"
	@echo "... sdr.s"
	@echo "... sdrworker.o"
	@echo "... sdrworker.i"
	@echo "... sdrworker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

